[package]
name = "wallpaper-engine-kde-rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "wallpaper_engine_kde_rs"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
chrono = "0.4.26"
cstr = "0.2.11"
qmetaobject = "0.2.9"
